### ISSUE TITLE
Message customization in error response

### ISSUE THREAD

**Issue by HubertLipinski** [timb-103/nuxt-rate-limit#3]
### Additional context
I'm currently working on a project using nuxt-rate-limit for my endpoints and while querying the API on the front end, I came across the need to display a translated error message containing information about the remaining lock time. 
I'm wondering if adding a configuration option for custom error message would be an option worth considering.

### Alternatives considered
I'm aware that this can be accomplished by using Nuxt's `onResponse() => {}` interceptor and reading the `'x-ratelimit-reset'` header as such:

```typescript
const { data, error } = await useFetch('/api/test', {
  onResponse: ({ response }) => {
    const seconds = response.headers.get('x-ratelimit-reset')
    // do other stuff
  },
});
```

But this could be better alternative
```typescript
const { data, error } = await useFetch('/api/test');
watch(error, (error) => {
  const statusMessage = error.statusMessage // already translated message
})
```

### Suggestion
Adding a `statusMessage` configuration option to `nuxtRateLimit` allowing user to set a custom error response. 

#### Example

```typescript
// nuxt.config.ts
nuxtRateLimit: {
  enabled: true,
  statusMessage: 'Lorem ipsum in :value: seconds', // template for error message, :value: holds remaining seconds
  routes: {
      // api routes
    },
  },
},
```
---

 I think that adding such option is worth considering, some might want to translate or return a completely different response than the standard 'Too many requests. Please try again in xyz seconds.

I'm more than happy to help with this issue.

**Comment by HubertLipinski** [comment]
I've opened PR #4 adressing this issue

**Comment by timb-103** [comment]
Awesome, merging!
